branches:
  only:
    - 'master'
    - 'develop'
    - 'ruby20'

language: ruby
rvm:
  - 2.0.0


env:
  - DB=postgres BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=other
  - DB=postgres BUILD_TYPE=cucumber
  - DB=mysql BUILD_TYPE=cucumber


bundler_args: "--without development production heroku"
before_install: "./script/ci/before_install.sh"
script: "./script/ci/build.sh"


notifications:
  irc:
    channels:
      - "irc.freenode.org:6667#diaspora-dev"
